jobs: 100
use-singularity: True
keep-going: True
rerun-incomplete: True
printshellcmds: True
max-jobs-per-second: 10
max-status-checks-per-second: 1
latency-wait: 40
retries: 1

cluster:
  mkdir -p slurm_output/ &&
  sbatch
    --partition={resources.partition}
    --cpus-per-task={resources.cpus}
    --mem={resources.mem_mb}
    --job-name={rule}-{wildcards}
    --output=slurm_output/{rule}-{wildcards}-%j.out
default-resources:
  - mem_mb=500
  - cpus=1
