# Please check the parameters, and adjust them according to your needs

# Project name
PROJECT: Awesome_experience

# ================== Control of the workflow ==================

## Do you want to download FASTQ files from public from Sequence Read Archive (SRA) ? 
SRA: no  # yes or no
# If set to "yes", the workflow will stop after the QC to let you decide whether you want to trim your raw data or not. 
# In order to run the rest of the workflow, you have to set it to "no".

## Do you need to do quality control?
QC: yes  # yes or no
# If set to "yes", the workflow will stop after the QC to let you decide whether you want to trim your raw data or not. 
# In order to run the rest of the workflow, you have to set it to "no".

## Do you need to do trimming?
TRIMMED: yes  # yes or no

## Do you need to do mapping and feature counting?
MAPPING: yes # yes or no

## Which mapping reference do you want to use? Genome or transcriptome?
REFERENCE: genome  # "genome" or "transcriptome"

## Do you want to study the repeats?
REPEATS: yes # yes or no

## Do you want to do Differential Expression Analysis (DEA)?
DEA: yes  # yes or no

# ================== Shared parameters for some or all of the sub-workflows ==================

## key file if the data is stored remotely, otherwise leave it empty
KEY: 

## the path to fastq files
READSPATH: /shared/projects/YourProjectName/Raw_fastq  # we recommend to always use full paths such as /shared/projects/YourProjectName/Raw_Fastq

## the meta file describing the experiment settings
METAFILE: /shared/projects/YourProjectName/RASflow_EDC/configs/metadata.tsv

## paths for intermediate final results
BIGDATAPATH: /shared/projects/YourProjectName/RASflow_EDC/data # for big files
RESULTPATH: /shared/projects/YourProjectName/RASflow_EDC/results

## is the sequencing paired-end or single-end?
END: pair  # "pair" or "single"

## maximum number of cores you want to allocate to one job of the workflow (mapping and feature counting)
NCORE: 32 

## maximum number of jobs running in parallel
NJOBS: 100

# ================== Configuration for Quality Control ==================

## All required params have already been defined in the public params

# ================== Configuration for trimming ==================

## Number of trimmed bases
## put "no" for TRIM3 and TRIM5 if you don't want to trim a fixed number of bases. 
TRIM5: no #  integer or "no", remove N bp from the 5' end of reads. This may be useful if the qualities were very poor, or if there is some sort of unwanted bias at the 5' end.
TRIM3: no # integer or "no", remove N bp from the 3' end of reads AFTER adapter/quality trimming has been performed.

# ================== Configuration for quantification using transcriptome ==================

## transcriptome file
TRANS: /shared/banks/homo_sapiens/hg38/transcriptome/gencode.v41.transcripts.fa # tests on going

## Do you need to do gene-level differential expression analysis?
GENE_LEVEL: yes  # yes or no. If "no", ignore the following 3 parameters.
## If "yes", specify the corresponding dataset in ENSEMBL for your interested organism or provide your own tx2gene
ENSEMBL: yes  # yes or no. Specify whether you're using transcriptome from Ensembl 
EnsemblDataSet: hsapiens_gene_ensembl  # only if ENSEMBL was set to "yes". 
## If you're not using ENSEMBL, you have to provide your homemade tx2gene file (two columns, 1st col: transcript ID; 2nd col: gene ID)
TX2GENE: tx2gene_custom.tsv  # only if ENSEMBL was set to "no"

# ================== Configuration for alignment to genome and feature count ==================

## aligner
ALIGNER: HISAT2 # "STAR" or "HISAT2"

## genome and annotation files
INDEXPATH: /shared/banks/homo_sapiens/hg38/hisat2 # folder containing index files
INDEXBASE: genome # for hisat2, base of the name of the index files (ie genome.1.ht2)
ANNOTATION: /shared/projects/YourProjectName/RASflow_EDC/gtf/gencode.v34.annotation.gtf # GTF file  

## bigwig option
BWSTRANDED: yes # "no": bw merging forward and reverse reads, "yes": get 2 bw files, one forward and one reverse; "both": get the two bw per strand as well as the merge one. 

## tool for feature count
COUNTER: featureCounts # "featureCounts" or "htseq-count" or "STARcount" (only with STAR aligner, --quantMode GeneCounts option) or "TEcount" (if REPEATS: yes)

## counting options
COUNTOPTIONS: "-M --fraction" # add extra options for the counter (for featureCounts or htseq-count only). 
# featureCounts: '-O' (set allowMultiOverlap to TRUE), '-M' (set countMultiMappingReads to TRUE), '--fraction'.
# htseq-count: -m <mode> ; --nonunique=<nonunique mode>; for instance "-m intersection-nonempty --nonunique=all" ... see https://htseq.readthedocs.io
ATTRIBUTE: gene_id  # the attribute used in annotation file. It's usually "gene_id", but double check that since it may also be "gene", "ID"...
STRAND: reverse # "no", "yes", "reverse". For stranded=no, a read is considered overlapping with a feature regardless of whether it is mapped to the same or the opposite strand as the feature. For stranded=yes and single-end reads, the read has to be mapped to the same strand as the feature. For paired-end reads, the first read has to be on the same strand and the second read on the opposite strand. For stranded=reverse, these rules are reversed.
FEATURE: transcript # "exon", "gene", "transcript", ... depending on your GTF file and on the feature you're interested in.
SPLITBY: 50000000 # To get efficient counting, the big bam files have to be split into smaller files. Put here the number of reads per sub-file. ie 50000000 for featureCounts, 20000000 for htseq-count. 

# ================== Configuration for repeat analysis ==================

GTFTE: /shared/projects/YourProjectName/RASflow_EDC/gtf/mm39_TE_rmsk.gtf # GTF ANNOTATION file for repeats, must be adapted to have the FEATURE you chose ("exon", "gene", "transcript") as 3rd column. 


# ================== Configuration for DEA ==================

## Do you want to start the workflow directly from the count tables obtained independently? If yes, give the path of your count tables. 
FROMCOUNTS: no   # put 'no' when using the whole workflow, or the path of your count tables. Format: one file / sample named {sample}_countGenes.tsv, 2 columns gene'\tab'count. 

## Do you want to use edgeR or DESeq2 to do DEA?
DEATOOL: DESeq2 # "edgeR" or "DESeq2"? DESeq2 is recommended for transcriptome-based DEA

## Is your experiment designed in a pair-wise way?
PAIR: no  # Is this a pair test or not? (yes or no). For instance 2 samples from the same patient taken at different times.

## the comparison(s) you want to do. If multiple comparisons, specify each pair (CONTROL & TREAT) in order respectively
CONTROL: ["J0_WT","J0_WT","J10_WT","J0_KO"]
TREAT: ["J0_KO","J10_WT","J10_KO","J10_KO"]
## length of 'CONTROL' should agree with that of 'TREAT'
## what you fill in there should agree with the "group" column in metadata.tsv

FILTER: yes  # Filter out low expressed transcripts/genes or not? (yes or no) It's better to be set to "yes".
